params:
  hidden_size: 512
  bottleneck_size: 64
  emphasis: 0.8
  dropout_ratio: 0.2

optimizer:
  init_lr: 3e-5
  lr_gamma: 0.995

scheduler:
  gamma: 0.995

earlystopper:
  min_delta: 1e-7
  patience: 50
  verbose: 1

noise_ratio:
  num: 0.25
  cat: 0.25

batch_size: 512
iterations: 3000

eval_verbose: 1

loss_weight:
  cat: 0.2
  num: 0.8

path: res/models
name: bottleneck_dae
result: bottleneck_dae_64_dw
