fold: 5
params:
#  learning_rate: 0.001
  iterations: 10000
#  max_depth: 7
  eval_metric: AUC
  loss_function: Logloss
#  l2_leaf_reg: 70
  early_stopping_rounds: 100

name: catboost

path: res/models
result: catboost_raw_dw
seed: 42
verbose: 500