folds: 1
params:
#  learning_rate: 0.001
  iterations: 15000
#  max_depth: 7
  eval_metric: AUC
  loss_function: Logloss
  task_type: GPU
  devices: '1'
#  l2_leaf_reg: 70
  early_stopping_rounds: 1000

name: catboost

path: res/models
result: catboost_1to7_fi
seed: 42
verbose: 500