params:
  hidden_size: 500
  emphasis: 0.8

optimizer:
  init_lr: 3e-5
  lr_gamma: 0.995

scheduler:
  gamma: 0.995

earlystopper:
  min_delta: 1e-7
  patience: 50
  verbose: 1

noise_ratio:
  num: 0.25
  cat: 0.25

batch_size: 512
num_workers: 64
iterations: 3000

eval_verbose: 1

loss_weight:
  cat: 0.2
  num: 0.8

path: res/models
name: deepstack_dae
result: deepstack_dae_with_dw
