# v2
folds: 1
params:
  boosting: dart
  learning_rate: 0.005
  objective: binary
  num_leaves: 100
  lambda_l2: 2
  lambda_l1: 0.0001
  feature_fraction: 0.7
  bagging_fraction: 0.3
  bagging_freq: 10
  max_depth: -1
  min_data_in_leaf: 64
  early_stopping_rounds: 100
  seed: 42
  verbose: -1

path: res/models
name: lgbm
result: lgbm_5fold_dae_standard_jb

num_boost_round: 15000
verbose: 500


# v1
#folds: 10
#params:
#  boosting: dart
#  learning_rate: 0.01
#  objective: binary
#  num_leaves: 100
#  lambda_l2: 2
#  lambda_l1: 0.0001
#  feature_fraction: 0.2
#  bagging_fraction: 0.5
#  bagging_freq: 10
#  min_data_in_leaf: 40
#  early_stopping_rounds: 100
#  seed: 42
#  verbose: -1
#
#path: res/models
#name: lgbm
#result: lgbm_10fold_dw
#
#num_boost_round: 10500
#verbose: 500
