folds: 1
params:
  booster: dart
  learning_rate: 0.005
  max_leaves: 100
  colsample_bytree: 0.7
  subsample: 0.3
  max_depth: 30
  tree_method: gpu_hist
  eval_metric: logloss
  gpu_id: 5
  early_stopping_rounds: 100
  seed: 42
  verbose: True

name: xgboost
num_boost_round: 15000

path: res/models
result: xgboost_test
seed: 42
verbose: 500