fold: 5
params:
  learning_rate: 0.001
  iterations: 30000
  max_depth: 7
  loss_function: Logloss
  l2_leaf_reg: 70

name: xgboost
early_stopping_rounds: 500
path: res/model
result: xgboost
seed: 42
verbose: 500