#defaults:
#  - dataset: dataset_with_dw
#  - model: mlp
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml

defaults:
  - dataset: dataset_dae
  - model: bottleneck_dae
  - features: features_jb_v2
  - preprocessing: preprocessing_for_ml_v4

output:
  before_path: ${dataset.root}/dataset/dae/df_nondefault_reconstructed_before.parquet
  after_path: ${dataset.root}/dataset/dae/df_nondefault_reconstructed_after.parquet
  representation_path: ${dataset.root}/dataset/dae/df_nondefault_representation.parquet
  confidence_path: ${dataset.root}/dataset/dae/df_nondefault_confidence.parquet

#  path: res/output
#  name: ${model.result}_test_2.csv


#representation:
#  path: res/models
#  result: deepstack_dae