
defaults:
  - dataset: dataset
  - model: tabnet
  - features: features_jb
  - preprocessing: preprocessing_for_ml_v2

preprocessor_applicator:
  path: res/preprocessor
  refresh: False

output:
  path: res/latent
  name: ${model.result}_train_tmp_latent.parquet

