#hydra:
#  run:
#    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
#  output_subdir: null

#defaults:
#  - dataset: dataset_with_dw
#  - model: mlp
#  - features: features_with_dw
#  - preprocessing: preprocessing
#
#representation:
#  path: res/models
#  result: deepstack_dae_1500_dw

defaults:
  - dataset: dataset
  - model: mlp_3
  - features: features_with_dw_v2
  - preprocessing: preprocessing

representation:
  path: res/models
  result: deepstack_dae_4500_dw_v2

output:
  path: res/output
  name: ${model.result}_test_2.csv

#representation:
#  path: res/models
#  result: transformer_dae_1024_dw_v2