#hydra:
#  run:
#    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
#  output_subdir: null

#defaults:
#  - dataset: dataset_with_dw
#  - model: mlp
#  - features: features_with_dw
#  - preprocessing: preprocessing
#
#representation:
#  path: res/models
#  result: deepstack_dae_1500_dw

defaults:
  - dataset: dataset_dae
  - model: deepstack_dae
  - features: features_jb_v2
  - preprocessing: preprocessing_for_ml_v3

#representation:
#  path: res/models
#  result: deepstack_dae_4500_standard

output:
  path: res/output
  name: ${model.result}_test.csv