#hydra:
#  run:
#    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
#  output_subdir: null

defaults:
  - dataset: dataset
  - model: deepstack_dae
  - features: features
  - preprocessing: preprocessing

#representation:
#  path: res/models
#  result: deepstack_dae_with_dw

#defaults:
#  - dataset: dataset_with_dw
#  - model: mlp
#  - features: features_with_dw
#  - preprocessing: preprocessing
#
#representation:
#  path: res/models
#  result: deepstack_dae