
defaults:
  - dataset: dataset_dae
  - model: gmm_dae
  - features: features_jb_v2
  - preprocessing: preprocessing_for_ml_v2

output:
  confidence_path: ${dataset.root}/dataset/gmm_dae/df_gamma.csv

#  path: res/output
#  name: ${model.result}_test_2.csv


#representation:
#  path: res/models
#  result: deepstack_dae