#defaults:
#  - dataset: dataset_with_dw
#  - model: catboost
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset
  - model: catboost
  - features: features_jb
  - preprocessing: preprocessing_for_ml

#representation:
#  path: res/models
#  result: gmm_dae_test_qt_2048

output:
  path: res/output
  name: ${model.result}_8_test.csv

#representation:
#  path: res/models
#  result: deepstack_dae