#defaults:
#  - dataset: dataset_with_dw
#  - model: mlp
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset_with_dw
  - model: mlp
  - features: features_with_dw
  - preprocessing: preprocessing

output:
  path: res/output
  name: ${model.result}.csv

#representation:
#  path: res/models
#  result: bottleneck_dae_with_dw #deepstack_dae_with_dw