#defaults:
#  - dataset: dataset_with_dw
#  - model: mlp
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset
  - model: catboost
  - features: features
  - preprocessing: preprocessing_for_ml

output:
  path: res/output
  name: ${model.result}_test_2.csv

#representation:
#  path: res/models
#  result: deepstack_dae