#defaults:
#  - dataset: dataset_with_dw
#  - model: catboost
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset_dae
  - model: lgbm
  - features: features_jb
  - preprocessing: preprocessing_for_ml_v3

representation:
  path: res/models
  result: deepstack_dae_4500_standard

output:
  path: res/output
  name: ${model.result}_test.csv

#representation:
#  path: res/models
#  result: deepstack_dae