defaults:
  - dataset: dataset
  - model: catboost
  - features: features
  - preprocessing: preprocessing

output:
  path: res/output
  name: ${model.result}.csv

representation:
  path: res/models
  result: deepstack_dae