#defaults:
#  - dataset: dataset_with_dw
#  - model: catboost
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset
  - model: lgbm
  - features: features_with_dw_v2
  - preprocessing: preprocessing_for_ml

#representation:
#  path: res/models
#  result: deepstack_dae_4500_dw

#representation:
#  path: res/models
#  result: deepstack_dae