#defaults:
#  - dataset: dataset_with_dw
#  - model: catboost
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset3
  - model: mlp_3
  - features: features_css
  - preprocessing: preprocessing_v2

#representation:
#  path: res/models
#  result: transformer_dae_1024_dw_v2

#representation:
#  path: res/models
#  result: deepstack_dae