#defaults:
#  - dataset: dataset_with_dw
#  - model: catboost
#  - features: features_with_dw
#  - preprocessing: preprocessing_for_ml


defaults:
  - dataset: dataset
  - model: mlp
  - features: features_with_dw_v2
  - preprocessing: preprocessing

representation:
  path: res/models
  result: transformer_dae_1024_dw_v2

#representation:
#  path: res/models
#  result: deepstack_dae