root: /home/peoplefund/workspace/jihwan-css/CSS

train: ${dataset.root}/dataset/train/catboost/df_1_to_2_seg1.parquet
#train: ${dataset.root}/dataset/train/df_1_to_2_all_light.parquet
#test: ${dataset.root}/dataset/test/df_05_jb_light.parquet
test: /data/cds_lc_raw/2022-08/all.parquet

save_path: ${dataset.root}/dataset/test/df_05_jb_light_saved.csv

target_name: target

seed: 42

num_workers: 32

device: 'cuda:1'

