root: /home/peoplefund/workspace/jihwan-css/CSS

# 12, 1월 train, valid + DW 대출 정보
train: ${dataset.root}/df_cds_proxy.parquet
# 12, 1월 test or 2월 전체
test: ${dataset.root}/df_cds_proxy_test.parquet

target_name: target

seed: 42

num_workers: 48
